name: "Bitfocus Companion"
description: "Bitfocus Companion for Home Assistant"
version: "0.2.9"
slug: "bitfocus_companion"
init: false
arch:
  - aarch64
  - amd64
startup: application
boot: auto
webui: "http://[HOST]:[PORT:8000]/"
panel_icon: "mdi:remote"
map:
  - type: addon_config
    read_only: false
ports:
  8000/tcp: 8000
  16622/tcp: 16622
  16623/tcp: 16623
  28492/tcp: 28492
ports_description:
  8000/tcp: "Web interface"
  16622/tcp: "Satellite API"
  16623/tcp: "WebSocket (Elgato Plugin)"
  28492/tcp: "Additional port"
usb: true
build_args:
  BUILD_ARCH: '|arch|'








